version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Using enhanced custom build environment"
      - node -v
      - npm -v
      - docker --version
      - echo Getting GitHub token from Secrets Manager...
      - echo Installing dependencies...
      - npm install
      - npm install supertest # Install supertest explicitly in the install phase
  pre_build:
    commands:
      - echo Running security checks...
      - npm audit
      - echo Running linting...
      - npx eslint . || true
  build:
    commands:
      - echo Running tests...
      - npm test # Runs Jest tests
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Running post-build security scans...
      - pip3 list --outdated
      - echo Preparing for deployment...
      - echo Build completed on `date`

artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**/*
  discard-paths: no

reports:
  jest-reports:
    files:
      - 'test-report.xml'
    file-format: JUNITXML

cache:
  paths:
    - '/root/.npm/**/*'  # Caching npm dependencies
    - 'node_modules/**/*' # Caching node_modules to speed up future builds
