version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Using enhanced custom build environment"
      - node -v
      - npm -v
      - docker --version
      - echo Getting GitHub token from Secrets Manager...
  pre_build:
    commands:
      - echo Cleaning up old dependencies...
      - rm -rf node_modules package-lock.json  # Clean old node_modules and package-lock.json
      - echo Installing dependencies...
      - npm install  # Install fresh dependencies
  build:
    commands:
      - echo Running tests...
      - npm test  # Run tests with Jest
      - echo Building the application...
      - npm run build  # Run the build command (optional)
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**/*
  discard-paths: no

reports:
  jest-reports:
    files:
      - 'test-report.xml'
    file-format: JUNITXML

cache:
  paths:
    - 'node_modules/**/*'
