version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Using enhanced custom build environment"
      - node -v
      - npm -v
      - docker --version
      - echo Getting GitHub token from Secrets Manager...
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github-token --query SecretString --output text | jq -r .token)
      - git config --global url."https://$GITHUB_TOKEN@github.com/".insteadOf "https://github.com/"
      - echo Installing dependencies...
      - npm install
      - npm install --save-dev chai  # Install chai for testing
      - npm install supertest  # If needed for supertest as well

  pre_build:
    commands:
      - echo Running security checks...
      - npm audit
      - echo Running linting...
      - npx eslint . || true

  build:
    commands:
      - echo Running tests...
      - npm test  # This will run the Mocha tests

  post_build:
    commands:
      - echo Packaging the Lambda function...
      - zip -r function.zip index.js app.js node_modules package.json
      - echo Build completed on `date`

artifacts:
  files:
    - function.zip
  discard-paths: yes

reports:
  jest-reports:
    files:
      - 'test-report.xml'
    file-format: JUNITXML

cache:
  paths:
    - 'node_modules/**/*'
